root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  # Updated path to match your project structure
  cmd = "go build -o ./tmp/main.exe ./cmd"
  bin = "tmp/main.exe"
  full_bin = "./tmp/main.exe"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "migrations"]
  include_dir = []
  exclude_file = []
  log = "air.log"
  delay = 1000 # ms
  stop_on_error = true
  send_interrupt = false
  kill_delay = 500 # ms

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true